config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  resources :projects
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :employee
  belongs_to :project
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :assignments, dependent: :destroy
  has_many :projects, through: :assignments
end

app/models/project.rb
# project.rb
class Project < ApplicationRecord
    has_many :assignments
    has_many :employees, through: :assignments
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: %i[ show edit update destroy ]

  # GET /assignments or /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1 or /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
    @employees = Employee.all
    @projects = Project.all
  end
  
  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments or /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to assignment_url(@assignment), notice: "Assignment was successfully created." }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1 or /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to assignment_url(@assignment), notice: "Assignment was successfully updated." }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1 or /assignments/1.json
  def destroy
    @assignment.destroy!

    respond_to do |format|
      format.html { redirect_to assignments_url, notice: "Assignment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assignment_params
      params.require(:assignment).permit(:employee_id, :project_id, :workload)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy!

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :departament, :skills)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/assignments/_assignment.html.erb
<div id="<%= dom_id assignment %>">
  <p>
    <strong>Empleado:</strong>
    <%= assignment.employee_id %>
  </p>

  <p>
    <strong>Proyecto:</strong>
    <%= assignment.project_id %>
  </p>

  <p>
    <strong>Carga de trabajo:</strong>
    <%= assignment.workload %>
  </p>

</div>

app/views/assignments/_form.html.erb
<%= form_with(model: assignment) do |form| %>
  <% if assignment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
        <% assignment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <label style="display: block">Empleado</label>
    <%# <%= form.label :employee_id, style: "display: block" %> 
    <%= form.select :employee_id, @employees.map { |employee| [employee.name, employee.id] } %>
  </div>

 
  <div>
  <label style="display: block">Proyecto</label>
    <%# <%= form.label :project_id, style: "display: block" %> 
    <%= form.select :project_id, @projects.map { |project| [project.name, project.id] } %>
  </div>

  <div>
  <label style="display: block">Carga de trabajo</label>
    <%# <%= form.label :workload, style: "display: block" %>
    <%= form.number_field :workload %>
  </div>

  <div>
    <%= form.submit %>
  </div>
  
  

  


<% end %>

app/views/assignments/edit.html.erb
<h1>Editar assignacion</h1>

<%= render "form", assignment: @assignment %>

<br>

<div>
  <%= link_to "Mostrar esta assignacion", @assignment %> |
  <%= link_to "Volver a assignaciones", assignments_path %>
</div>

app/views/assignments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Asignaciones</h1>

<div id="assignments">
  <% @assignments.each do |assignment| %>
    <%= render assignment %>
    <p>
      <%= link_to "Mostrar esta assignacion", assignment %>
    </p>
  <% end %>
</div>

<%= link_to "Nueva assignacion", new_assignment_path %>

app/views/assignments/new.html.erb
<h1>Nueva assignacion</h1>

<%= render "form", assignment: @assignment %>

<br>

<div>
  <%= link_to "Volver a las assignaciones", assignments_path %>
</div>

app/views/assignments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @assignment %>

<div>
  <%= link_to "Editar esta assignacion", edit_assignment_path(@assignment) %> |
  <%= link_to "Volver a assignaciones", assignments_path %>

  <%= button_to "Elimar esta assignacion", @assignment, method: :delete %>
</div>

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>Nombre:</strong>
    <%= employee.name %>
  </p>

  <p>
    <strong>Departamento:</strong>
    <%= employee.departament %>
  </p>

  <p>
    <strong>Habilidades:</strong>
    <%= employee.skills %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :departament, style: "display: block" %>
    <%= form.text_field :departament %>
  </div>

  <div>
    <%= form.label :skills, style: "display: block" %>
    <%= form.text_field :skills %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editar empleado</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Mostrar este empleado", @employee %> |
  <%= link_to "Volver a empleados", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Empleados</h1>

<div id="employees">
  <% @employees.each do |employee| %>
    <%= render employee %>
    <p>
      <%= link_to "Mostrar este empleado", employee %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo empleado", new_employee_path %>

app/views/employees/new.html.erb
<h1>Nuevo Empleado</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Regresar a empleados", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Editar empleado", edit_employee_path(@employee) %> |
  <%= link_to "Volver a empleados", employees_path %>

  <%= button_to "Eliminar este empleado", @employee, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OptimizacionRrhh</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

<%= stylesheet_link_tag 'application', media: 'all' %> 
<%= stylesheet_link_tag 'custom_styles', media: 'all' %> 

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<head>
  <title>Proyectos</title>
  <%= stylesheet_link_tag 'project' %>
</head>


<div id="<%= dom_id project %>">
  <p>
    <strong>Nombre:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Descripción:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editar Proyecto</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Mostar este proyecto", @project %> |
  <%= link_to "Volver a proyectos", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Proyectos</h1>

<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Mostrar este proyecto", project %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo proyecto", new_project_path %>

app/views/projects/new.html.erb
<h1>Nuevo proyecto</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Volver a proyectos", projects_path %>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Editar este proyecto", edit_project_path(@project) %> |
  <%= link_to "Volver a proyectos", projects_path %>

  <%= button_to "Eliminar este proyecto", @project, method: :delete %>
</div>